### ISSUE TITLE
No possibility to discover API limits

### ISSUE THREAD

**Issue by hobovsky** [danshannon/javastravav3api#176] opened 2017-04-19 14:20 UTC
Hi Dan,

I encountered some difficulties when I wanted to handle a **StravaAPIRateLimitException** in my application. All information needed is returned by Strava in **X-Ratelimit-Limit / X-Ratelimit-Usage** response headers, however this information is not exposed in any way by JavaStrava high level API (or at least I could not find it). Could you please consider one (or more) of following improvements?

- Subclass **StravaAPIRateLimitException** to indicate if it is a short-time limit or long-time limit exhausted - most basic information that would satisfy my use case, I can wait 15 minutes to complte my task, but I'd like to report an error when task cannot be completed today,
 - Store **X-Ratelimit-Limit / X-Ratelimit-Usage** values in the exception object - convenient to read, would provide all information delivered by Strava and allow us to handle most of exceptional scenarios,
 - Store **X-Ratelimit-Limit / X-Ratelimit-Usage** in the StravaResponse - maybe it would be the better place, as this information logically belongs to response, or
 - Expose **X-Ratelimit-Limit / X-Ratelimit-Usage** values, possibly obtained from most recent call, by new method(s) of **Strava**  class - this approach would provide rate limit usage information to applications and allow applications to track the API usage (and throttle calls down or use any other strategy of 'limit conservation').

I see that currently values of **X-Ratelimit-Usage** response headers are ignored, and I believe that they might be quite useful for applications. Is there any way to reach them (with JavaStrava API) currently? If not, would you consider any improvement in this topic?

Thanks and best regards,
     Maciek

**Comment by danshannon** [comment] 2017-04-23 12:07
Have a look at the code for `javastrava.api.v3.rest.util.RetrofitClientResponseInterceptor`

It sets:

- `StravaConfig.RATE_LIMIT` and `StravaConfig,RATE_LIMIT_DAILY` to the currently enforced rate limits from the `X-Ratelimit-Limit` header; and 
- `StravaServiceImpl.requestRate` and `StravaServiceImpl.requestRateDaily` to the actual usage numbers from the `X-Ratelimit-Usage` header.

If you catch a `StravaRateLimitException`, you should be able to use those values to interrogate what the problem is. In addition, there are utility methods `StravaServiceImpl.requestRatePercentage()` and `StravaServiceImpl.requestRateDailyPercentage()` which will tell you how much of current and/or daily quotas you have currently used.

Hope this helps!

Cheers

Dan

**Comment by danshannon** [comment] 2017-04-23 12:08
I will move these values and methods into the `Strava` class as part of the 2.0.0 release

**Comment by danshannon** [comment] 2017-04-23 12:11
See #178

**Comment by hobovsky** [comment] 2017-04-24 06:07
Thanks a lot, I will try your suggestions out, somehow I missed it. I probably haven't looked for solution hard enough :)

**Comment by danshannon** [comment] 2017-04-25 01:27
No worries Maciek - I will close this issue, if you have any other problems just raise a new one

Cheers

Dan

**Closed by danshannon** 2017-04-25 01:27 UTC
